`timescale 1ns/1ps

(* blackbox *)
module mlx_pe_top (
    input  wire         clk,
    input  wire         rst_n,
    input  wire         cfg_valid_i,
    input  wire [4:0]   cfg_addr_i,
    input  wire [63:0]  cfg_word_i,
    input  wire [4:0]   fetch_addr_i,
    output wire [63:0]  fetch_word_o,
    output wire         configured_o,
    input  wire         tag_configure_i,
    input  wire [3:0]   tag_configure_id_i,
    input  wire [7:0]   tag_trip_count_i,
    input  wire [5:0]   tag_frontier_i,
    input  wire         tag_ready_i,
    input  wire         tag_issue_i,
    input  wire [3:0]   tag_issue_id_i,
    input  wire         tag_complete_i,
    input  wire [3:0]   tag_complete_id_i,
    input  wire [3:0]   tag_query_id_i,
    output wire [15:0]  tag_active_vector_o,
    output wire [15:0]  tag_ready_vector_o,
    output wire [15:0]  tag_done_vector_o,
    output wire [7:0]   tag_query_trip_count_o,
    output wire [5:0]   tag_query_frontier_o,
    input  wire [31:0]  pipeline_class_i,
    input  wire [3:0]   pipeline_ready_i,
    output wire [3:0]   issue_valid_o,
    output wire [15:0]  issue_tag_o,
    input  wire [3:0]   rf_read_addr_a_i,
    input  wire [3:0]   rf_read_addr_b_i,
    input  wire [3:0]   rf_read_addr_c_i,
    output wire [511:0] rf_read_data_a_o,
    output wire [511:0] rf_read_data_b_o,
    output wire [511:0] rf_read_data_c_o,
    input  wire         rf_write_enable_i,
    input  wire [3:0]   rf_write_addr_i,
    input  wire [511:0] rf_write_data_i,
    input  wire         network_valid_i,
    input  wire signed [4:0] network_dx_i,
    input  wire signed [4:0] network_dy_i,
    input  wire [3:0]   network_destination_register_i,
    input  wire [3:0]   network_tag_i,
    input  wire [63:0]  network_payload_i,
    output wire         network_valid_o,
    output wire signed [4:0] network_dx_o,
    output wire signed [4:0] network_dy_o,
    output wire [2:0]   network_route_o,
    output wire [1:0]   network_consumed_hops_o,
    output wire         network_delivered_o,
    output wire [63:0]  network_payload_o,
    input  wire         fu_valid_i,
    input  wire [3:0]   fu_op_i,
    input  wire [511:0] fu_vector_a_i,
    input  wire [511:0] fu_vector_b_i,
    input  wire [511:0] fu_vector_c_i,
    output wire         fu_valid_o,
    output wire [511:0] fu_vector_result_o,
    output wire         fu_illegal_o
);
endmodule
