`timescale 1ns/1ps

(* blackbox *)
module mlx_array_pe_tile (
    input  wire         clk,
    input  wire         rst_n,
    input  wire         cfg_valid_i,
    input  wire [4:0]   cfg_addr_i,
    input  wire [63:0]  cfg_word_i,
    input  wire         cfg_instruction_count_valid_i,
    input  wire [5:0]   cfg_instruction_count_i,
    input  wire         launch_i,
    input  wire [3:0]   tile_id_i,
    output wire         spm_req_valid_o,
    output wire         spm_req_write_o,
    output wire [7:0]   spm_req_addr_o,
    output wire [511:0] spm_req_wdata_o,
    input  wire         spm_req_grant_i,
    input  wire         spm_rsp_valid_i,
    input  wire [511:0] spm_rsp_rdata_i,
    input  wire         route_in_valid_i,
    input  wire signed [4:0] route_in_dx_i,
    input  wire signed [4:0] route_in_dy_i,
    input  wire [3:0]   route_in_destination_register_i,
    input  wire [3:0]   route_in_tag_i,
    input  wire [3:0]   route_in_source_i,
    input  wire [511:0] route_in_data_i,
    output wire         route_in_ready_o,
    output wire         route_out_valid_o,
    output wire [4:0]   route_out_target_o,
    output wire signed [4:0] route_out_dx_o,
    output wire signed [4:0] route_out_dy_o,
    output wire [3:0]   route_out_destination_register_o,
    output wire [3:0]   route_out_tag_o,
    output wire [3:0]   route_out_source_o,
    output wire [511:0] route_out_data_o,
    output wire [1:0]   route_out_hops_o,
    input  wire         route_out_grant_i,
    input  wire         xfer_complete_i,
    output wire         xfer_complete_valid_o,
    output wire [3:0]   xfer_complete_source_o,
    output wire         execution_active_o,
    output wire         router_active_o,
    output wire         instruction_issue_o,
    output wire         load_issue_o,
    output wire         store_issue_o,
    output wire         compute_issue_o,
    output wire         xfer_issue_o,
    output wire         stall_o,
    output wire         delivery_conflict_o
);
endmodule
