cmake_minimum_required(VERSION 3.16)
project(mlx_clocked_device LANGUAGES CXX)
add_subdirectory(../physical_device physical-wire)
add_library(mlx_clocked_device STATIC device.cc)
target_include_directories(mlx_clocked_device PUBLIC ${CMAKE_CURRENT_SOURCE_DIR} ../../simulator_ext/model_io)
target_link_libraries(mlx_clocked_device PUBLIC mlx_matrix_wire)
target_compile_options(mlx_clocked_device PRIVATE -Wall -Wextra -Werror)
add_executable(clocked-device-driver ../../tests/clocked_device_driver.cc ../physical_device/mapped_memory.cc)
target_link_libraries(clocked-device-driver PRIVATE mlx_clocked_device)
target_compile_options(clocked-device-driver PRIVATE -Wall -Wextra -Werror)
