cmake_minimum_required(VERSION 3.16)
project(mlx_event_schedule LANGUAGES CXX)
find_package(PkgConfig REQUIRED)
find_package(OpenSSL REQUIRED)
pkg_check_modules(JSONCPP REQUIRED IMPORTED_TARGET jsoncpp)
add_library(mlx_event_schedule STATIC event_schedule.cc)
target_sources(mlx_event_schedule PRIVATE ../model_events/completion_window.cc)
target_link_libraries(mlx_event_schedule PUBLIC PkgConfig::JSONCPP OpenSSL::Crypto)
target_compile_features(mlx_event_schedule PUBLIC cxx_std_17)
target_compile_options(mlx_event_schedule PRIVATE -Wall -Wextra -Werror)
add_executable(mlx-event-schedule main.cc)
target_link_libraries(mlx-event-schedule PRIVATE mlx_event_schedule)
target_compile_options(mlx-event-schedule PRIVATE -Wall -Wextra -Werror)
