#!/usr/bin/env python3
"""Promote one nested VCD scope to a standalone activity root."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any


def extract_scope(
    source: Path,
    destination: Path,
    scope: str,
    *,
    ports_only: bool = False,
    timestamp_scale: int = 1,
) -> dict[str, Any]:
    if timestamp_scale < 1:
        raise ValueError("timestamp_scale must be a positive integer")
    lines = source.read_text(errors="strict").splitlines()
    requested = scope.split(".")
    stack: list[str] = []
    variables: list[str] = []
    codes: set[str] = set()
    timescale: list[str] = []
    collecting_timescale = False
    definitions_end = None
    for index, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith("$scope "):
            stack.append(stripped.split()[2])
        elif stripped.startswith("$upscope"):
            stack.pop()
        elif stripped.startswith("$timescale"):
            collecting_timescale = True
            timescale.append(line)
            if stripped.endswith("$end"):
                collecting_timescale = False
        elif collecting_timescale:
            timescale.append(line)
            if stripped.endswith("$end"):
                collecting_timescale = False
        elif stripped.startswith("$var ") and stack == requested:
            tokens = stripped.split()
            reference = tokens[4]
            if ports_only and not (
                reference.endswith(("_i", "_o"))
                or reference in {"clk", "rst_n"}
            ):
                continue
            variables.append(line)
            codes.add(tokens[3])
        elif stripped.startswith("$enddefinitions"):
            definitions_end = index
            break
    if definitions_end is None:
        raise ValueError("VCD has no enddefinitions")
    if not variables:
        raise ValueError(f"VCD scope has no direct variables: {scope}")

    output = [
        "$date",
        "  generated by MLX scope extractor",
        "$end",
        "$version",
        "  mlxsim H199 exact transition subset",
        "$end",
        *(timescale or ["$timescale 1ps $end"]),
        "$scope module component_activity $end",
        *variables,
        "$upscope $end",
        "$enddefinitions $end",
    ]
    timestamps = 0
    transitions = 0
    in_dump = False
    for line in lines[definitions_end + 1 :]:
        stripped = line.strip()
        if stripped == "$dumpvars":
            output.append(line)
            in_dump = True
            continue
        if stripped == "$end" and in_dump:
            output.append(line)
            in_dump = False
            continue
        if stripped.startswith("#"):
            output.append(f"#{int(stripped[1:]) * timestamp_scale}")
            timestamps += 1
            continue
        if not stripped or stripped.startswith("$"):
            continue
        code = stripped.split()[-1] if stripped[0] in "brs" else stripped[1:]
        if code in codes:
            output.append(line)
            transitions += 1
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text("\n".join(output) + "\n")
    return {
        "source": str(source),
        "destination": str(destination),
        "scope": scope,
        "variables": len(variables),
        "unique_codes": len(codes),
        "timestamps": timestamps,
        "transitions": transitions,
        "ports_only": ports_only,
        "timestamp_scale": timestamp_scale,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("destination", type=Path)
    parser.add_argument("scope")
    parser.add_argument("--ports-only", action="store_true")
    parser.add_argument("--timestamp-scale", type=int, default=1)
    args = parser.parse_args()
    result = extract_scope(
        args.source,
        args.destination,
        args.scope,
        ports_only=args.ports_only,
        timestamp_scale=args.timestamp_scale,
    )
    print(result)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
