cmake_minimum_required(VERSION 3.16)
project(mlx_control_leaf LANGUAGES CXX)
add_subdirectory(../tensor_model tensor-model)
add_library(mlx_control_leaf INTERFACE)
target_include_directories(mlx_control_leaf INTERFACE ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(mlx_control_leaf INTERFACE mlx_tensor_values)
add_executable(mlx-control-leaf main.cc)
target_link_libraries(mlx-control-leaf PRIVATE mlx_control_leaf)
target_compile_options(mlx-control-leaf PRIVATE -Wall -Wextra -Werror)
